<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../BuildingBlocks/Otex.BuildingBlocks.Application/Otex.BuildingBlocks.Application.csproj"/>
        <ProjectReference Include="..\Otex.Micros.Identity.Domain\Otex.Micros.Identity.Domain.csproj" />
    </ItemGroup>

</Project>
