<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Otex.BuildingBlocks.Application\Otex.BuildingBlocks.Application.csproj" />
      <ProjectReference Include="..\Otex.BuildingBlocks.ServiceDefaults\Otex.BuildingBlocks.ServiceDefaults.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
      <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.4.6" />
      <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.4.6" />
      <PackageReference Include="MassTransit" Version="8.5.8" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.8" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Quartz.Extensions.Hosting" Version="3.19.1" />
      <PackageReference Include="Scrutor" Version="7.0.0" />
      <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    </ItemGroup>

</Project>
