// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Otex.Micros.Applicants.Infrastructure.Data;

#nullable disable

namespace Otex.Micros.Applicants.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicantsDbContext))]
    partial class ApplicantsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cooperation")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Otex.Micros.Applicants.Domain.Cooperation.Models.Cooperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeOfActivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Description", "Otex.Micros.Applicants.Domain.Cooperation.Models.Cooperation.Description#Description", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Description");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fullname", "Otex.Micros.Applicants.Domain.Cooperation.Models.Cooperation.Fullname#Fullname", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Firstname")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Firstname");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Lastname");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "IsVerified", "Otex.Micros.Applicants.Domain.Cooperation.Models.Cooperation.IsVerified#IsVerified", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Value")
                                .HasColumnType("boolean")
                                .HasColumnName("IsVerified");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "Otex.Micros.Applicants.Domain.Cooperation.Models.Cooperation.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Province");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Mobile", "Otex.Micros.Applicants.Domain.Cooperation.Models.Cooperation.Mobile#Mobile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Mobile");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ReserveDateTime", "Otex.Micros.Applicants.Domain.Cooperation.Models.Cooperation.ReserveDateTime#ReservationDateTime", b1 =>
                        {
                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ReservationDateTime");
                        });

                    b.HasKey("Id");

                    b.ToTable("Cooperation", "cooperation");
                });
#pragma warning restore 612, 618
        }
    }
}
